name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: "node version: ${{matrix.node}} os: ${{matrix.os}}"
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [18.*]
      fail-fast: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "node.js version: ${{matrix.node}}"
        uses: actions/setup-node@v3
        with:
          check-latest: true
          node-version: ${{matrix.node}}
          os: ${{matrix.os}}
          cache: 'npm'
      - name: npm10
        run: npm i -g 'npm@10.*' --registry=https://registry.npmjs.org
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
