name: test

on: [push, pull_request]

jobs:
  build:
    name: "node version: ${{matrix.node}} os: ${{matrix.os}}"
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14.*, 18.*]
      fail-fast: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: "node.js version: ${{matrix.node}}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
